version: '3.8'

services:
  tor-scraper:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tor-selenium-scraper
    volumes:
      # ソースコードをマウント（開発時）
      - ../src:/app/src:ro
      # ログ出力用（オプション）
      - ../logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TOR_PROXY_PORT=9050
    # 必要に応じてポートを公開
    ports:
      - "9050:9050"  # Tor SOCKS proxy
      - "9051:9051"  # Tor control port
    restart: unless-stopped
    # メモリ制限（オプション）
    mem_limit: 1g
    # CPU制限（オプション）
    cpus: 0.5

  # 開発用のワンショット実行
  tor-scraper-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tor-selenium-dev
    volumes:
      - ../src:/app/src:ro
      - ../logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TOR_PROXY_PORT=9050
    profiles:
      - dev
    command: ["uv", "run", "src/tor_scraper.py"]